version: "3"

services:
  db:
    build:
      context: .
      dockerfile: infrastructure/database/Dockerfile
    ports:
      - "5432:5432"
    restart: always
  
  backend:
    build:
      context: .
      dockerfile: event_manager/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always